server:
  port: 9091

spring:
  application:
    name: msvc-wallet
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/walletDB
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:configserver:http://localhost

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      efaultZone: http://localhost:8761/eureka
